const enum ErrorCode {
  AUTH_EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN",
  AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  AUTH_NOT_FOUND = "AUTH_NOT_FOUND",
  AUTH_TOO_MANY_ATTEMPTS = "AUTH_TOO_MANY_ATTEMPTS",
  AUTH_UNAUTHORIZED_ACCESS = "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",

  // Database Errors
  DATABASE_ERROR = "DATABASE_ERROR",
  DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR",
  DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR",
  DATABASE_TRANSACTION_ERROR = "DATABASE_TRANSACTION_ERROR",
  DATABASE_MODEL_ERROR = "DATABASE_MODEL_ERROR",
  DATABASE_MIGRATION_ERROR = "DATABASE_MIGRATION_ERROR",
  DATABASE_SYNC_ERROR = "DATABASE_SYNC_ERROR",
  DATABASE_VALIDATION_ERROR = "DATABASE_VALIDATION_ERROR",
  DATABASE_ASSOCIATION_ERROR = "DATABASE_ASSOCIATION_ERROR",

  // User Errors
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_PASSWORD_MISMATCH = "USER_PASSWORD_MISMATCH",
  USER_EMAIL_NOT_FOUND = "USER_EMAIL_NOT_FOUND",
  USER_EMAIL_ALREADY_EXISTS = "USER_EMAIL_ALREADY_EXISTS",
  USER_INVALID_TOKEN = "USER_INVALID_TOKEN",

  // Session Errors
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  SESSION_ALREADY_EXISTS = "SESSION_ALREADY_EXISTS",
  SESSION_INVALID_TOKEN = "SESSION_INVALID_TOKEN",
  SESSION_EXPIRED = "SESSION_EXPIRED",

  // Access Control Errors
  ACCESS_FORBIDDEN = "ACCESS_FORBIDDEN",
  ACCESS_UNAUTHORIZED = "ACCESS_UNAUTHORIZED",

  // Validation and Resource Errors
  VALIDATION_ERROR = "VALIDATION_ERROR",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREADY_EXISTS",

  // System Errors
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  VERIFICATION_ERROR = "VERIFICATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  UNKNOWN = "UNKNOWN",
  BAD_REQUEST = "BAD_REQUEST",
}

export { ErrorCode };